import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
export const TUBE_WIDTH = SCREEN_WIDTH * 0.15;
export const BALL_SIZE = TUBE_WIDTH * 0.9;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradient: {
    flex: 1,
    padding: 20,
  },
  header: {
    marginTop: 20,
    marginBottom: 30,
  },
  backButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    padding: 12,
    borderRadius: 20,
    alignSelf: 'flex-start',
    marginBottom: 20,
  },
  backButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  gameContainer: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    position: 'relative',
  },
  tubesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    gap: 20,
  },
  tube: {
    width: TUBE_WIDTH,
    height: TUBE_WIDTH * 5,
    backgroundColor: 'rgba(0, 128, 128, 0.1)',
    borderRadius: TUBE_WIDTH * 0.2,
    justifyContent: 'flex-end',
    alignItems: 'center',
    padding: TUBE_WIDTH * 0.1,
    marginHorizontal: 10,
    borderWidth: 4,
    borderColor: 'rgba(0, 128, 128, 0.5)',
    borderTopWidth: 0,
    borderBottomLeftRadius: TUBE_WIDTH * 0.7,
    borderBottomRightRadius: TUBE_WIDTH * 0.7,
    position: 'relative',
  },
  selectedTube: {
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    borderWidth: 2,
    borderColor: '#FFF',
  },
  errorTube: {
    borderColor: '#FF0000',
    backgroundColor: 'rgba(255, 0, 0, 0.1)',
  },
  ball: {
    width: BALL_SIZE,
    height: BALL_SIZE,
    borderRadius: BALL_SIZE / 2,
    marginVertical: -1,
    shadowColor: '#000',
    shadowOffset: { width: -2, height: -2 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 5,
  },
  errorBall: {
    transform: [{scale: 1.1}],
    shadowColor: '#FF0000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
  },
  successAnimation: {
    position: 'absolute',
    width: SCREEN_WIDTH,
    height: SCREEN_WIDTH,
    zIndex: 1000,
  },
  emptyBall: {
    backgroundColor: 'transparent',
  },
  hiddenBall: {
    opacity: 0,
  },
  draggedBall: {
    width: BALL_SIZE,
    height: BALL_SIZE,
    borderRadius: BALL_SIZE / 2,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    zIndex: 1000,
    position: 'absolute',
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
  },
  statsText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  undoButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    padding: 10,
    borderRadius: 15,
    marginHorizontal: 5,
  },
  hintButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    padding: 10,
    borderRadius: 15,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
  },
  hintOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    zIndex: 100,
  },
  hintArrow: {
    width: 30,
    height: 30,
    backgroundColor: '#FFF',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  validTargetTube: {
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderWidth: 2,
    borderColor: '#4CAF50',
  },
  selectedBall: {
    transform: [{scale: 1.1}],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  completedTube: {
    borderColor: 'rgba(165, 42, 42, 1)', // brown
  },
  tubeTop: {
    position: 'absolute',
    top: -6,
    width: TUBE_WIDTH * 1.5,
    height: 12,
    backgroundColor: 'rgba(0, 128, 128, 0.3)',
    borderRadius: 5,
    shadowColor: 'rgba(0, 128, 128, 0.2)',
    shadowOffset: { width: -2, height: -2 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    backdropFilter: 'blur(5px)',
  },
}); 